/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalCalendarRouteImport } from './routes/portal.calendar'
import { Route as ClickupCallbackRouteImport } from './routes/clickup.callback'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalCalendarRoute = PortalCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => PortalRoute,
} as any)
const ClickupCallbackRoute = ClickupCallbackRouteImport.update({
  id: '/clickup/callback',
  path: '/clickup/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/workspace': typeof WorkspaceRoute
  '/clickup/callback': typeof ClickupCallbackRoute
  '/portal/calendar': typeof PortalCalendarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/workspace': typeof WorkspaceRoute
  '/clickup/callback': typeof ClickupCallbackRoute
  '/portal/calendar': typeof PortalCalendarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/workspace': typeof WorkspaceRoute
  '/clickup/callback': typeof ClickupCallbackRoute
  '/portal/calendar': typeof PortalCalendarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/login'
    | '/portal'
    | '/workspace'
    | '/clickup/callback'
    | '/portal/calendar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/console'
    | '/login'
    | '/portal'
    | '/workspace'
    | '/clickup/callback'
    | '/portal/calendar'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/login'
    | '/portal'
    | '/workspace'
    | '/clickup/callback'
    | '/portal/calendar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRoute
  ClickupCallbackRoute: typeof ClickupCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/calendar': {
      id: '/portal/calendar'
      path: '/calendar'
      fullPath: '/portal/calendar'
      preLoaderRoute: typeof PortalCalendarRouteImport
      parentRoute: typeof PortalRoute
    }
    '/clickup/callback': {
      id: '/clickup/callback'
      path: '/clickup/callback'
      fullPath: '/clickup/callback'
      preLoaderRoute: typeof ClickupCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PortalRouteChildren {
  PortalCalendarRoute: typeof PortalCalendarRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalCalendarRoute: PortalCalendarRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  WorkspaceRoute: WorkspaceRoute,
  ClickupCallbackRoute: ClickupCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
